[project]
name = "second-brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rdp2802", email = "rishi.dcei@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.141.1",
    "gh>=0.0.4",
    "google-genai>=2.9.0",
    "numpy>=2.5.2",
    "ollama>=0.6.2",
    "pandas>=3.0.5",
    "pgvector>=0.5.0",
    "psycopg>=3.3.4",
    "psycopg2>=2.9.12",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.0",
    "sqlalchemy>=2.0.52",
    "transformers>=5.15.1",
]

[project.scripts]
second-brain = "second_brain:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "venv",
]
