"""removed knowledge type, since there is no strong requirement for the same/

Revision ID: 01f2b306612d
Revises: aa7d8245f1b1
Create Date: 2026-09-01 16:14:44.056776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01f2b306612d'
down_revision: Union[str, Sequence[str], None] = 'aa7d8245f1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_summary', 'knowledge_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_summary', sa.Column('knowledge_type', postgresql.ENUM('STORY', 'HABIT', 'BELIEF', 'GOAL', 'PREFERENCE', name='knowledge_type_enum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
