"""Added Tables: ChatRetrievedSummary, ChatRetrievedDetail.Renamed MessageBlockSummaries to MessageBlock. Added Join Table between Messages, MessageBlock Tables.

Revision ID: 2cf3fa16f9d7
Revises: 01f2b306612d
Create Date: 2026-09-07 16:19:02.128266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf3fa16f9d7'
down_revision: Union[str, Sequence[str], None] = '01f2b306612d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
