"""A lil nomenclature change in session table (user->user_id)

Revision ID: 54b50762864c
Revises: a65c6c63c199
Create Date: 2026-09-19 13:49:06.701959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b50762864c'
down_revision: Union[str, Sequence[str], None] = 'a65c6c63c199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('session_user_fkey'), 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(op.f('session_user_fkey'), 'session', 'user', ['user'], ['id'], ondelete='CASCADE')
    op.drop_column('session', 'user_id')
    # ### end Alembic commands ###
