"""Creating migration before nomenclature and structural Audit and Changes of DB

Revision ID: 6f8df89397be
Revises: 2cf3fa16f9d7
Create Date: 2026-09-12 17:36:06.314705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f8df89397be'
down_revision: Union[str, Sequence[str], None] = '2cf3fa16f9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_block',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('order_in_chat', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_retrieved_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_summary_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['knowledge_summary_id'], ['knowledge_summary.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_join_block',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['message_block.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'message_id', name='uq_message_join_block_block_message')
    )
    op.create_table('chat_retrieved_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_summary_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_detail_id', sa.UUID(), nullable=False),
    sa.Column('retrieved_summary_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['knowledge_detail_id'], ['knowledge_detail.id'], ),
    sa.ForeignKeyConstraint(['knowledge_summary_id'], ['knowledge_summary.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['retrieved_summary_id'], ['chat_retrieved_summary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message_block_summary')
    op.add_column('chat', sa.Column('last_summary_message_order', sa.Integer(), nullable=False))
    op.add_column('chat', sa.Column('last_memory_extracted_message_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'last_memory_extracted_message_order')
    op.drop_column('chat', 'last_summary_message_order')
    op.create_table('message_block_summary',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('end_message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('message_block_summary_chat_id_fkey')),
    sa.ForeignKeyConstraint(['end_message_id'], ['message.id'], name=op.f('message_block_summary_end_message_id_fkey')),
    sa.ForeignKeyConstraint(['start_message_id'], ['message.id'], name=op.f('message_block_summary_start_message_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('message_block_summary_pkey'))
    )
    op.drop_table('chat_retrieved_detail')
    op.drop_table('message_join_block')
    op.drop_table('chat_retrieved_summary')
    op.drop_table('message_block')
    # ### end Alembic commands ###
