"""Added Foreign Key MessageBlock.user_id and the SQLAlchemy relationship between them

Revision ID: 751ff93fcf78
Revises: 83501ba4c126
Create Date: 2026-09-12 19:32:31.040908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751ff93fcf78'
down_revision: Union[str, Sequence[str], None] = '83501ba4c126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_block', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('message_block', sa.Column('content', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'message_block', 'user', ['user_id'], ['id'])
    op.drop_column('message_block', 'summary_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_block', sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message_block', type_='foreignkey')
    op.drop_column('message_block', 'content')
    op.drop_column('message_block', 'user_id')
    # ### end Alembic commands ###
