"""add summarisation and ingestion going_on flags to chat

Revision ID: 7e451d9ab18f
Revises: c45b8adbc95e
Create Date: 2026-09-14 15:52:56.571572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e451d9ab18f'
down_revision: Union[str, Sequence[str], None] = 'c45b8adbc95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('summarisation_going_on', sa.Boolean(), nullable=False))
    op.add_column('chat', sa.Column('ingestion_going_on', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'ingestion_going_on')
    op.drop_column('chat', 'summarisation_going_on')
    # ### end Alembic commands ###
