"""Renamed KnowledgeDetail, KnowledgeSummary, ChatRetrievedSummary, ChatRetrievedDetail to MemoryDetail, MemorySummary, RetrievedSummary, RetrievedDetail. Refined SQLAlchemy relationships to have consistency. Joined Messages and MemoryDetail via a Join Table and added SQLAlchemy relationship between them. Renamed Chats, Messages to Chat, Message

Revision ID: 83501ba4c126
Revises: 6f8df89397be
Create Date: 2026-09-12 18:22:04.688378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '83501ba4c126'
down_revision: Union[str, Sequence[str], None] = '6f8df89397be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('retrieval_count', sa.Integer(), nullable=False),
    sa.Column('last_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('memory_summary_index', 'memory_summary', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('memory_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['memory_summary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('memory_detail_index', 'memory_detail', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('detail_join_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detail_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['memory_detail.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieved_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('memory_summary_id', sa.UUID(), nullable=False),
    sa.Column('memory_detail_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['memory_detail_id'], ['memory_detail.id'], ),
    sa.ForeignKeyConstraint(['memory_summary_id'], ['memory_summary.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieved_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('memory_summary_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['memory_summary_id'], ['memory_summary.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_retrieved_detail')
    op.drop_table('chat_retrieved_summary')
    op.drop_index(op.f('knowledge_detail_index'), table_name='knowledge_detail', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_table('knowledge_detail')
    op.drop_index(op.f('knowledge_summary_index'), table_name='knowledge_summary', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_table('knowledge_summary')
    op.add_column('chat', sa.Column('last_summarisation_message_order', sa.Integer(), nullable=False))
    op.add_column('chat', sa.Column('last_ingestion_message_order', sa.Integer(), nullable=False))
    op.drop_column('chat', 'last_memory_extracted_message_order')
    op.drop_column('chat', 'last_summary_message_order')
    op.add_column('message', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.drop_column('message', 'context_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('context_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'user_id')
    op.add_column('chat', sa.Column('last_summary_message_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chat', sa.Column('last_memory_extracted_message_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('chat', 'last_ingestion_message_order')
    op.drop_column('chat', 'last_summarisation_message_order')
    op.create_table('knowledge_summary',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False),
    sa.Column('relevancy_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('retrieval_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_retrieved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('knowledge_summary_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_summary_pkey'))
    )
    op.create_index(op.f('knowledge_summary_index'), 'knowledge_summary', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('knowledge_detail',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_message_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False),
    sa.Column('detail_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('knowledge_detail_chat_id_fkey')),
    sa.ForeignKeyConstraint(['summary_id'], ['knowledge_summary.id'], name=op.f('knowledge_detail_summary_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('knowledge_detail_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_detail_pkey'))
    )
    op.create_index(op.f('knowledge_detail_index'), 'knowledge_detail', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('chat_retrieved_summary',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_summary_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('chat_retrieved_summary_chat_id_fkey')),
    sa.ForeignKeyConstraint(['knowledge_summary_id'], ['knowledge_summary.id'], name=op.f('chat_retrieved_summary_knowledge_summary_id_fkey')),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('chat_retrieved_summary_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chat_retrieved_summary_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_retrieved_summary_pkey'))
    )
    op.create_table('chat_retrieved_detail',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_summary_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('retrieved_summary_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('chat_retrieved_detail_chat_id_fkey')),
    sa.ForeignKeyConstraint(['knowledge_detail_id'], ['knowledge_detail.id'], name=op.f('chat_retrieved_detail_knowledge_detail_id_fkey')),
    sa.ForeignKeyConstraint(['knowledge_summary_id'], ['knowledge_summary.id'], name=op.f('chat_retrieved_detail_knowledge_summary_id_fkey')),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('chat_retrieved_detail_message_id_fkey')),
    sa.ForeignKeyConstraint(['retrieved_summary_id'], ['chat_retrieved_summary.id'], name=op.f('chat_retrieved_detail_retrieved_summary_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chat_retrieved_detail_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_retrieved_detail_pkey'))
    )
    op.drop_table('retrieved_summary')
    op.drop_table('retrieved_detail')
    op.drop_table('detail_join_message')
    op.drop_index('memory_detail_index', table_name='memory_detail', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('memory_detail')
    op.drop_index('memory_summary_index', table_name='memory_summary', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('memory_summary')
    # ### end Alembic commands ###
