"""Adding Session table for authentication and authorization

Revision ID: a65c6c63c199
Revises: e5ca0f70c853
Create Date: 2026-09-19 13:42:46.075081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65c6c63c199'
down_revision: Union[str, Sequence[str], None] = 'e5ca0f70c853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user', sa.UUID(), nullable=False),
    sa.Column('valid_till', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
