"""Added nullability constraints, ondelete functionality and did some other fixes. As for V1, this ORM and DB is final (I hope it indeed is)

Revision ID: c45b8adbc95e
Revises: 751ff93fcf78
Create Date: 2026-09-13 13:27:14.234814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45b8adbc95e'
down_revision: Union[str, Sequence[str], None] = '751ff93fcf78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_user_id_fkey'), 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_detail_join_message_detail_message', 'detail_join_message', ['detail_id', 'message_id'])
    op.drop_constraint(op.f('detail_join_message_message_id_fkey'), 'detail_join_message', type_='foreignkey')
    op.drop_constraint(op.f('detail_join_message_detail_id_fkey'), 'detail_join_message', type_='foreignkey')
    op.create_foreign_key(None, 'detail_join_message', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detail_join_message', 'memory_detail', ['detail_id'], ['id'], ondelete='CASCADE')
    op.alter_column('memory_detail', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('memory_detail_chat_id_fkey'), 'memory_detail', type_='foreignkey')
    op.drop_constraint(op.f('memory_detail_user_id_fkey'), 'memory_detail', type_='foreignkey')
    op.drop_constraint(op.f('memory_detail_summary_id_fkey'), 'memory_detail', type_='foreignkey')
    op.create_foreign_key(None, 'memory_detail', 'chat', ['chat_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'memory_detail', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memory_detail', 'memory_summary', ['summary_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('memory_summary_user_id_fkey'), 'memory_summary', type_='foreignkey')
    op.create_foreign_key(None, 'memory_summary', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_message_chat_order', 'message', ['chat_id', 'order_in_chat'])
    op.drop_constraint(op.f('message_chat_id_fkey'), 'message', type_='foreignkey')
    op.drop_constraint(op.f('message_user_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_message_block_chat_order', 'message_block', ['chat_id', 'order_in_chat'])
    op.drop_constraint(op.f('message_block_user_id_fkey'), 'message_block', type_='foreignkey')
    op.drop_constraint(op.f('message_block_chat_id_fkey'), 'message_block', type_='foreignkey')
    op.create_foreign_key(None, 'message_block', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message_block', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('message_join_block_chat_id_fkey'), 'message_join_block', type_='foreignkey')
    op.drop_constraint(op.f('message_join_block_message_id_fkey'), 'message_join_block', type_='foreignkey')
    op.drop_constraint(op.f('message_join_block_block_id_fkey'), 'message_join_block', type_='foreignkey')
    op.create_foreign_key(None, 'message_join_block', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message_join_block', 'message_block', ['block_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message_join_block', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('retrieved_detail_memory_summary_id_fkey'), 'retrieved_detail', type_='foreignkey')
    op.drop_constraint(op.f('retrieved_detail_memory_detail_id_fkey'), 'retrieved_detail', type_='foreignkey')
    op.drop_constraint(op.f('retrieved_detail_user_id_fkey'), 'retrieved_detail', type_='foreignkey')
    op.drop_constraint(op.f('retrieved_detail_message_id_fkey'), 'retrieved_detail', type_='foreignkey')
    op.drop_constraint(op.f('retrieved_detail_chat_id_fkey'), 'retrieved_detail', type_='foreignkey')
    op.create_foreign_key(None, 'retrieved_detail', 'memory_detail', ['memory_detail_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retrieved_detail', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retrieved_detail', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retrieved_detail', 'memory_summary', ['memory_summary_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retrieved_detail', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('retrieved_summary_memory_summary_id_fkey'), 'retrieved_summary', type_='foreignkey')
    op.drop_constraint(op.f('retrieved_summary_message_id_fkey'), 'retrieved_summary', type_='foreignkey')
    op.drop_constraint(op.f('retrieved_summary_user_id_fkey'), 'retrieved_summary', type_='foreignkey')
    op.drop_constraint(op.f('retrieved_summary_chat_id_fkey'), 'retrieved_summary', type_='foreignkey')
    op.create_foreign_key(None, 'retrieved_summary', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retrieved_summary', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retrieved_summary', 'memory_summary', ['memory_summary_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'retrieved_summary', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'retrieved_summary', type_='foreignkey')
    op.drop_constraint(None, 'retrieved_summary', type_='foreignkey')
    op.drop_constraint(None, 'retrieved_summary', type_='foreignkey')
    op.drop_constraint(None, 'retrieved_summary', type_='foreignkey')
    op.create_foreign_key(op.f('retrieved_summary_chat_id_fkey'), 'retrieved_summary', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('retrieved_summary_user_id_fkey'), 'retrieved_summary', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('retrieved_summary_message_id_fkey'), 'retrieved_summary', 'message', ['message_id'], ['id'])
    op.create_foreign_key(op.f('retrieved_summary_memory_summary_id_fkey'), 'retrieved_summary', 'memory_summary', ['memory_summary_id'], ['id'])
    op.drop_constraint(None, 'retrieved_detail', type_='foreignkey')
    op.drop_constraint(None, 'retrieved_detail', type_='foreignkey')
    op.drop_constraint(None, 'retrieved_detail', type_='foreignkey')
    op.drop_constraint(None, 'retrieved_detail', type_='foreignkey')
    op.drop_constraint(None, 'retrieved_detail', type_='foreignkey')
    op.create_foreign_key(op.f('retrieved_detail_chat_id_fkey'), 'retrieved_detail', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('retrieved_detail_message_id_fkey'), 'retrieved_detail', 'message', ['message_id'], ['id'])
    op.create_foreign_key(op.f('retrieved_detail_user_id_fkey'), 'retrieved_detail', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('retrieved_detail_memory_detail_id_fkey'), 'retrieved_detail', 'memory_detail', ['memory_detail_id'], ['id'])
    op.create_foreign_key(op.f('retrieved_detail_memory_summary_id_fkey'), 'retrieved_detail', 'memory_summary', ['memory_summary_id'], ['id'])
    op.drop_constraint(None, 'message_join_block', type_='foreignkey')
    op.drop_constraint(None, 'message_join_block', type_='foreignkey')
    op.drop_constraint(None, 'message_join_block', type_='foreignkey')
    op.create_foreign_key(op.f('message_join_block_block_id_fkey'), 'message_join_block', 'message_block', ['block_id'], ['id'])
    op.create_foreign_key(op.f('message_join_block_message_id_fkey'), 'message_join_block', 'message', ['message_id'], ['id'])
    op.create_foreign_key(op.f('message_join_block_chat_id_fkey'), 'message_join_block', 'chat', ['chat_id'], ['id'])
    op.drop_constraint(None, 'message_block', type_='foreignkey')
    op.drop_constraint(None, 'message_block', type_='foreignkey')
    op.create_foreign_key(op.f('message_block_chat_id_fkey'), 'message_block', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('message_block_user_id_fkey'), 'message_block', 'user', ['user_id'], ['id'])
    op.drop_constraint('uq_message_block_chat_order', 'message_block', type_='unique')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_user_id_fkey'), 'message', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('message_chat_id_fkey'), 'message', 'chat', ['chat_id'], ['id'])
    op.drop_constraint('uq_message_chat_order', 'message', type_='unique')
    op.drop_constraint(None, 'memory_summary', type_='foreignkey')
    op.create_foreign_key(op.f('memory_summary_user_id_fkey'), 'memory_summary', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'memory_detail', type_='foreignkey')
    op.drop_constraint(None, 'memory_detail', type_='foreignkey')
    op.drop_constraint(None, 'memory_detail', type_='foreignkey')
    op.create_foreign_key(op.f('memory_detail_summary_id_fkey'), 'memory_detail', 'memory_summary', ['summary_id'], ['id'])
    op.create_foreign_key(op.f('memory_detail_user_id_fkey'), 'memory_detail', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('memory_detail_chat_id_fkey'), 'memory_detail', 'chat', ['chat_id'], ['id'])
    op.alter_column('memory_detail', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'detail_join_message', type_='foreignkey')
    op.drop_constraint(None, 'detail_join_message', type_='foreignkey')
    op.create_foreign_key(op.f('detail_join_message_detail_id_fkey'), 'detail_join_message', 'memory_detail', ['detail_id'], ['id'])
    op.create_foreign_key(op.f('detail_join_message_message_id_fkey'), 'detail_join_message', 'message', ['message_id'], ['id'])
    op.drop_constraint('uq_detail_join_message_detail_message', 'detail_join_message', type_='unique')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key(op.f('chat_user_id_fkey'), 'chat', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
